---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flame
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    flame.georgesg/name: flame
    flame.georgesg/url: dev.flame.shokohsc.home
    flame.georgesg/type: app
    flame.georgesg/icon: fire
spec:
  rules:
  - host: dev.flame.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flame
            port:
              number: 80
  tls:
  - hosts:
    - dev.flame.shokohsc.home
    secretName: flame-cert
